config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  mount_uploader :profile_picture, PhotoUploader

  has_many :members
  has_many :teams, through: :members

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def user_score
    #find every teams for one user
    #
    list_teams = self.teams
      user_score = 0
    list_teams.each do |team|
      user_score += team.score
    end
    user_score
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in (@user)
      redirect_to user_path(current_user), notice: 'Signed in successfully.'
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?

    else

 session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order('created_at DESC')
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user

  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
    authorize @user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :id, :address, :profile_picture)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.erb
<% if member.team.present? %>

<%# if member.team.end_date.to_date > Date.today %>
<%# else %>
<%# end %>

<%# if member.team.team_picture.present? %>
<%#= cl_image_tag member.team.team_picture, class: "picture-card" %>
<%# else %>
<%#= cl_image_tag("default_fkhyps.png", class: "picture-card") %>
<%# end %>
<% if policy(member.team).show? %>
<% if member.team.city.present? %>
<div class="content">
  <div class="row card-challenge">
    <% if member.team.team_picture.present? %>
    <div class="card-picture" style="background-image: url('<%= cl_image_path member.team.city.picture %>');"></div>
    <% else %>
    <div class="card-picture" style="background-image: url('<%= image_path "tripin-brussels.png" %>');"></div>
    <% end %>
    <div class="card-title"><%= member.team.city.name %></div>
    <% if policy(member.team).destroy? %>
    <%= link_to team_path(member.team), method: :delete, class: "card-link" do %>
    <div class="card-score text-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#FFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <polyline points="3 6 5 6 21 6"/>
      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
      <line x1="10" y1="11" x2="10" y2="17"/>
      <line x1="14" y1="11" x2="14" y2="17"/>
    </svg>
  </div>
  <% end %>
  <% end %>
  <h3>From <%= member.team.start_date.strftime("%d")%> to <%= member.team.end_date.strftime("%d %B") %></h3>
  <%= link_to "", team_path(member.team.id) , class: "card-link" %>
</div>
</div>


   <!--  <li>From <%#= member.team.start_date.strftime("%d")%> to
   <%#= member.team.end_date.strftime("%d %B") %></li> -->
   <%#= member.team.score %>
   <% end %>

   <% end %>

   <%# if member.team.end_date.to_date > Date.today %>
   <%# else %>
   <%# end %>


   <% end %>

app/views/users/edit.html.erb
<div class="container">

  <h3>Edit your profile</h3>

  <%= simple_form_for @user, url: user_path do |u| %>
    <%= u.input :first_name, placeholder: "Your first name." %>
    <%= u.input :last_name, placeholder: "Your last name." %>
    <%= u.input :address, placeholder: "Your address." %>
    <%= u.input :profile_picture %>
    <%= u.input :profile_picture_cache, as: :hidden %>
    <%= u.submit %>

  <% end %>

  <%= link_to 'Go Back', user_path(@user) %>

</div>
<br>
<br>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 blue-bg">
      <div class="row abitpads">
        <div class="col-xs-4 right">
          <%= link_to user_path(current_user) do %>
          <% if current_user.facebook_picture_url.nil? %>
          <% unless current_user.profile_picture.nil?  %>
          <% if current_user.profile_picture.present? %>
          <%= cl_image_tag current_user.profile_picture, class: "avatar-profile", crop: :fill %>
          <% else %>
          <%= image_tag("default.png", class: "avatar-profile") %>
          <% end %>
          <% end %>
          <%else %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar-profile", crop: :fill %>
          <% end %>
          <% end %>
        </div>
        <div class="col-xs-8 ">
          <ul class="list-inline profile liltop">
            <li><%= current_user.first_name.capitalize %></li>
            <li class="profile-inline"><%= current_user.last_name.capitalize %></li>
            <li class="little-dates"><%= current_user.user_score %></li>
          </ul>
          <%= link_to "Edit profile", edit_user_path(current_user), method: :get, class: "profile opacity" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="row toppie middlemargin">
    <% if current_user.members.count > 0 %>
    <% current_user.members.each do |member| %>
    <div class="col-xs-12 col-sm-3">
      <%= render "card", member: member %>
    </div>
    <%end %>
    <% else %>
    <div class="text-center content toppadding">
      <h6>No trips yet !</h6>
      <p style="padding: 0 30px;"> Once you start a trip, all your adventures will live here.</p>
    </div>
    <% end %>
  </div>
  <div id="bottom" class="bottommenup text-center">
    <%= link_to "START A NEW TRIP", new_team_path, class: 'btn-main' %>
  </div>
</div>