config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_monkey.html.erb
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 487.048 487.048" style="enable-background:new 0 0 487.048 487.048;" xml:space="preserve">
<path id="XMLID_31_" d="M258.112,237.369l14.798,29.568c15.322,30.614,4.215,67.319-24.76,81.821
  c-0.051,0.026-0.103,0.051-0.154,0.076c-7.819,3.884-16.28,5.839-24.871,5.839c-6.846,0-13.774-1.24-20.531-3.735
  c-15.083-5.567-27.437-16.72-34.785-31.399l-14.797-29.568c-2.225-4.444-0.424-9.852,4.021-12.076
  c4.444-2.225,9.851-0.424,12.076,4.021l14.797,29.567c5.293,10.575,14.144,18.591,24.922,22.569
  c10.57,3.901,21.673,3.409,31.262-1.39c0.041-0.021,0.081-0.04,0.122-0.06c20.011-10.103,27.46-35.913,16.602-57.609l-14.798-29.568
  c-2.225-4.445-0.425-9.853,4.021-12.076C250.479,231.12,255.887,232.923,258.112,237.369z M303.684,36.481l-2.24,11.861
  c15.537,21.026,25.453,40.787,24.919,65.515c-0.59,27.314-13.751,58.378-42.564,100.254l21.436,42.83
  c11.07-36.502,26.174-86.213,38.121-102.677c15.512-21.381,40.458-31.091,63.558-24.734c15.506,4.266,28.139,15.081,35.571,30.454
  c7.235,14.966,8.655,32.527,3.999,49.45c-7.629,27.729-34.06,44.723-58.922,37.884c-24.862-6.842-38.881-34.967-31.251-62.694
  c5.523-20.079,24.798-32.354,42.97-27.354c18.167,4.999,28.455,25.403,22.933,45.485c-3.422,12.434-15.542,19.979-27.02,16.821
  c-5.698-1.568-10.501-5.645-13.179-11.185c-2.521-5.215-3.028-11.284-1.43-17.092c1.319-4.793,6.277-7.609,11.066-6.288
  c4.792,1.319,7.608,6.273,6.289,11.065c-0.435,1.579-0.332,3.212,0.281,4.479c0.301,0.623,0.848,1.417,1.749,1.665
  c1.635,0.439,4.071-1.271,4.889-4.242c2.89-10.511-1.753-20.988-10.352-23.354c-8.602-2.368-17.949,4.261-20.84,14.772
  c-4.997,18.16,3.379,36.356,18.671,40.564c15.292,4.203,31.796-7.144,36.792-25.304c3.5-12.718,2.488-25.801-2.849-36.84
  c-5.14-10.631-13.713-18.065-24.14-20.934c-15.794-4.345-33.149,2.7-44.214,17.95c-10.217,14.08-26.105,66.469-35.598,97.77
  c-2.923,9.639-5.488,18.098-7.549,24.449c1.706,12.663,0.72,25.415-2.694,37.458c7.002-0.696,14.148,0.089,21.046,2.386
  c8.986,2.991,16.771,8.286,22.701,15.317l9.771-4.89c17.299-8.656,38.416-1.625,47.075,15.671c1.068,2.135,1.246,4.607,0.492,6.872
  c-0.754,2.266-2.377,4.139-4.512,5.207l-39.889,19.963c-4.445,2.226-9.852,0.426-12.076-4.02l-10.359-20.697
  c-0.011-0.022-0.022-0.045-0.034-0.067c-3.873-7.738-10.569-13.52-18.854-16.278c-8.028-2.672-16.564-2.18-24.127,1.378
  c-8.686,15.156-21.76,28.015-38.5,36.422c-0.039,0.021-0.077,0.04-0.116,0.059c-16.319,8.169-34.327,11.229-52.122,9.044
  c-6.564,3.984-11.465,10.135-13.938,17.563c-2.758,8.286-2.144,17.11,1.729,24.849c0.014,0.028,0.028,0.056,0.042,0.084
  l10.353,20.683c1.068,2.135,1.245,4.606,0.491,6.871c-0.754,2.265-2.377,4.138-4.512,5.206l-39.89,19.963
  c-1.285,0.643-2.662,0.952-4.023,0.952c-2.759,0-5.456-1.271-7.205-3.601l-0.001-0.002c-0.323-0.432-0.607-0.891-0.848-1.372
  c-4.181-8.354-4.85-17.861-1.884-26.772s9.201-16.121,17.555-20.302l9.77-4.89c-2.075-8.962-1.647-18.368,1.345-27.354
  c2.125-6.386,5.415-12.166,9.664-17.104c-21.956-8.178-39.688-24.044-50.164-44.976l-24.58-49.113
  c-3.77,4.527-6.265,10.025-7.146,15.983l-11.842,80.195l28.777,22.104c1.893,1.454,3.131,3.601,3.441,5.968
  c0.311,2.366-0.332,4.76-1.786,6.652l-8.991,11.705c-4.832,6.291-11.847,10.327-19.752,11.363
  c-7.908,1.038-15.724-1.054-22.014-5.887c-6.291-4.831-10.327-11.847-11.363-19.752c-1.037-7.904,1.053-15.723,5.886-22.013
  l7.564-9.85l12.274-83.115c1.898-12.856,8.615-24.321,18.734-32.28c-1.525-10.803,0.143-21.851,4.831-31.779
  c-6.769,2.591-14.18,2.759-21.182,0.429c-6.259-2.084-11.585-5.963-15.406-11.145l-5.564,2.785
  c-7.094,3.552-15.167,4.119-22.732,1.602c-7.565-2.519-13.686-7.813-17.235-14.907c-3.55-7.092-4.119-15.165-1.601-22.729
  c2.519-7.564,7.812-13.686,14.905-17.236l6.222-3.114c-6.412-21.447-2.875-43.685,10.419-63.835
  C84.798,79.544,129.85,57.22,170.025,59.609c24.292,1.449,44.254,11.739,57.487,29.342l6.268-3.137
  c7.092-3.552,15.164-4.119,22.73-1.602c7.565,2.519,13.687,7.813,17.236,14.906c3.55,7.093,4.119,15.166,1.601,22.73
  c-2.518,7.565-7.812,13.687-14.906,17.236l-5.563,2.785c1.856,6.164,1.77,12.751-0.314,19.011
  c-2.331,7.001-6.906,12.833-13.038,16.698c12.615,2.578,23.97,9.402,32.142,19.377c50.421-75.986,38.305-105.303,10.91-141.109
  L249.8,49.279c-4.884-0.923-8.096-5.63-7.173-10.514l0.432-2.284H73.728c-4.971,0-9-4.029-9-9s4.029-9,9-9h173.348
  c5.252-12.807,18.97-20.628,33.084-17.96c10.264,1.938,18.307,8.956,22.02,17.96h146.041c4.971,0,9,4.029,9,9s-4.029,9-9,9H303.684z
   M286.375,28.74c-0.023-0.165-0.042-0.332-0.056-0.5c-0.654-4.902-4.378-9.064-9.498-10.031c-6.389-1.207-12.562,3.009-13.768,9.395
  l-1.069,5.659l23.162,4.375C285.147,37.637,286.47,29.796,286.375,28.74z M89.475,404.279l-3.508,4.567
  c-1.903,2.479-2.725,5.571-2.313,8.709c0.411,3.138,2.003,5.914,4.481,7.817s5.568,2.724,8.708,2.314
  c3.138-0.411,5.914-2.003,7.817-4.481l3.509-4.567L89.475,404.279z M190.639,454.064l-3.619-7.23l-8.517,4.263
  c-4.055,2.029-7.084,5.541-8.532,9.891c-0.419,1.26-0.69,2.542-0.814,3.828L190.639,454.064z M365.141,357.684l3.619,7.23
  l21.496-10.758c-4.87-2.987-11.126-3.474-16.599-0.734L365.141,357.684z M236.685,104.488l10.55,21.078l5.149-2.577
  c2.795-1.398,4.884-3.822,5.884-6.825c1-3.002,0.78-6.194-0.619-8.988c-1.398-2.795-3.822-4.885-6.825-5.884
  c-3.002-1.001-6.196-0.781-8.989,0.618L236.685,104.488z M70.037,214.253l-10.55-21.079l-5.15,2.578
  c-5.812,2.908-8.173,10.003-5.265,15.814c1.398,2.795,3.822,4.884,6.825,5.884c3.002,0.997,6.195,0.778,8.99-0.619L70.037,214.253z
   M106.267,224.707l-17.569-35.103c-7.997-15.981,1.31-35.144,22.129-45.563c11.613-5.813,23.258-7.127,32.672-4.377
  c3.442-9.186,11.474-17.719,23.089-23.532c20.819-10.421,41.735-6.383,49.732,9.597l17.568,35.104
  c1.629-1.522,2.866-3.446,3.595-5.638c1.147-3.444,0.895-7.107-0.71-10.314l-17.952-35.868
  c-12.135-24.248-33.816-30.479-49.868-31.436c-33.62-2.009-72.747,17.357-91.009,45.041c-8.727,13.229-16.527,34.197-4.13,58.968
  l16.323,32.612c0.008,0.016,0.016,0.031,0.023,0.046c0.007,0.016,0.015,0.03,0.022,0.046l1.585,3.166
  c1.605,3.207,4.386,5.605,7.829,6.751C101.789,224.937,104.072,225.102,106.267,224.707z M126.131,222.277
  c1.522,1.344,3.36,2.261,5.315,2.687c0.285,0.037,0.569,0.088,0.851,0.152c2.292,0.33,4.699-0.015,6.919-1.126
  c1.292-0.646,2.667-0.953,4.02-0.953c3.3,0,6.478,1.821,8.055,4.974c8.038,16.061,27.645,22.587,43.706,14.55
  c7.739-3.874,13.521-10.57,16.279-18.855c2.758-8.286,2.144-17.11-1.729-24.85c-2.225-4.445-0.425-9.852,4.02-12.076
  c2.214-1.108,3.928-2.825,5.04-4.847c0.122-0.276,0.257-0.547,0.405-0.809c0.826-1.817,1.19-3.834,1.026-5.854
  c-0.03-0.21-0.053-0.42-0.068-0.63c-0.169-1.248-0.544-2.489-1.138-3.678l-18.606-37.176c-4.215-8.425-17.606-5.545-25.58-1.557
  c-7.972,3.99-18.303,12.984-14.086,21.409c2.225,4.445,0.425,9.852-4.02,12.076c-4.444,2.226-9.852,0.425-12.077-4.02
  c-0.003-0.007-0.006-0.013-0.01-0.02c-4.228-8.4-17.603-5.523-25.568-1.537c-7.973,3.99-18.304,12.984-14.088,21.41l18.606,37.175
  c0.593,1.186,1.361,2.228,2.256,3.11C125.82,221.976,125.977,222.122,126.131,222.277z M264.366,215.5
  c-6.256-12.5-18.719-20.431-32.525-21.029c-0.976,1.266-2.059,2.458-3.245,3.564c3.248,10.13,3.198,21.02-0.242,31.354
  c-4.277,12.848-13.263,23.241-25.302,29.266c-22.566,11.293-49.642,4.067-63.834-15.889c-1.595,0.286-3.199,0.438-4.796,0.462
  c-6.239,9.128-8.204,20.38-5.537,30.916c0.05,0.172,0.095,0.345,0.135,0.518c0.659,2.456,1.57,4.87,2.74,7.206l25.4,50.751
  c8.822,17.628,24.063,30.793,42.915,37.068c3.86,1.285,7.772,2.248,11.705,2.892c0.335,0.033,0.667,0.085,0.995,0.155
  c14.917,2.235,30.081-0.12,43.77-6.946c0.034-0.018,0.068-0.035,0.103-0.052c29.418-14.724,44.785-46.497,40.131-77.396
  c-0.094-0.406-0.161-0.82-0.197-1.239c-1.19-7.081-3.438-14.103-6.815-20.851L264.366,215.5z M134.777,189.532
  c4.446-2.223,6.249-7.629,4.026-12.074c-2.222-4.445-7.626-6.248-12.074-4.027l-1.452,0.726c-4.446,2.223-6.249,7.629-4.026,12.074
  c1.577,3.154,4.755,4.979,8.057,4.979c1.352,0,2.725-0.306,4.017-0.951L134.777,189.532z M185.132,215.022
  c-0.012,0.491-0.176,1.255-0.886,2.105c-1.616,1.936-4.408,2.26-5.825,1.252c-4.051-2.88-9.671-1.928-12.549,2.124
  c-2.879,4.052-1.928,9.671,2.124,12.55c3.718,2.642,8.063,3.918,12.422,3.918c6.537,0,13.107-2.87,17.647-8.309
  c3.146-3.769,4.944-8.454,5.062-13.193c0.124-4.97-3.805-9.098-8.774-9.221C189.372,206.099,185.255,210.053,185.132,215.022z
   M170.395,204.209c1.352,0,2.724-0.306,4.015-0.95l1.453-0.726c4.447-2.222,6.251-7.627,4.03-12.073
  c-2.222-4.448-7.628-6.25-12.073-4.03l-1.453,0.726c-4.447,2.222-6.251,7.627-4.03,12.073
  C163.913,202.385,167.093,204.209,170.395,204.209z M184.617,163.528c1.355,0,2.731-0.308,4.026-0.956l1.452-0.728
  c4.443-2.227,6.24-7.635,4.013-12.078c-2.228-4.444-7.634-6.239-12.079-4.014l-1.452,0.728c-4.443,2.227-6.241,7.635-4.013,12.078
  C178.143,161.708,181.319,163.528,184.617,163.528z M221.461,306.238c1.356,0,2.733-0.308,4.027-0.957l1.451-0.728
  c4.443-2.229,6.239-7.637,4.01-12.079c-2.228-4.442-7.636-6.239-12.08-4.011l-1.451,0.728c-4.443,2.229-6.239,7.637-4.01,12.079
  C214.988,304.418,218.163,306.238,221.461,306.238z"/>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar-tripin navbar-tripin-fixed">
  <%= link_to root_path, class: "navbar-tripin navbar-tripin-fixed-brand" do %>
  <% if @team.present? && @challenge.present? %>
  <div class="smaller padss"><%= render "shared/tripinlogo" unless current_page?(team_challenge_path(@team, @challenge)) || current_page?(root_path) %></div>
  <% end %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <% if current_user.present? %>
    <% if user_signed_in? %>
    <!-- Profile picture and dropdown -->
    <div class="navbar-item">
      <% if current_user.profile_picture.present? %>
      <%= image_tag current_user.profile_picture, class: "avatar", :onclick => "openNav()" %>
      <% else %>
      <%= image_tag ("default.png"), class: "avatar", :onclick => "openNav()" %>

      <div id="myNav" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"></a>
        <% end %>

        <ul class="overlay-content">
          <div class="row bigbigspace">
            <div class="col-xs-2">
              <%= link_to user_path(current_user) do %>
              <% if current_user.facebook_picture_url.nil? %>
              <% unless current_user.profile_picture.nil?  %>
              <% if current_user.profile_picture.present? %>
              <%= cl_image_tag current_user.profile_picture, class: "avatar-nav", crop: :fill %>
              <% else %>
              <%= image_tag("default.png", class: "avatar-nav") %>
              <% end %>
              <% end %>
              <%else %>
              <%= image_tag current_user.facebook_picture_url, class: "avatar-nav", crop: :fill %>
              <% end %>
              <% end %>
            </div>
            <div class="col-xs-10">
              <ul class="list-inline profile liltop">
                <li><%= current_user.first_name.capitalize %></li>
                <li class="profile-inline"><%= current_user.last_name.capitalize %></li>
                <li class="little-dates"><%= current_user.user_score %></li>
              </ul>
              <%= link_to destroy_user_session_path, class: "profile opacity",  method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </div>
          </div>


          <li class="little-title">MY TRIPS</li>
          <ul class="cities yes">
            <% current_user.teams.each do |t| %>
            <% if t.city.present? %>
            <% if t.in_trip? %>
            <li> <ul class="list-inline"><li><%= link_to t.city.name, team_path(t), method: :get %></li>
            <li class="little-dates"><%= t.start_date.strftime("%d")%> <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
              <%= t.end_date.strftime("%d-%m") %></li></ul>
            </li>
            <% end %>
            <% end %>
            <% end %>
          </ul>
          <li class="cities"><%= link_to "New trip", root_path %></li>
          <li><hr align="left" width="10%" opacity="0.5"></li>
          <li>About</li>
          <li>Contact us</li>
        </ul>
      </div>
    </div>
  </div>
  <% else %>
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "loginpls" %>
  <% end %>
  <% end %>

  <!-- Mobile friendly -->
  <% if current_user.present? %>
  <% if user_signed_in? %>
  <div class="navbar-item hidden-md hidden-lg">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#143673
    " stroke-width="2" stroke-linecap="round" stroke-linejoin="round" onclick="openlilNav()">
    <line x1="3" y1="12" x2="21" y2="12"/>
    <line x1="3" y1="6" x2="21" y2="6"/>
    <line x1="3" y1="18" x2="21" y2="18"/>
  </svg>
  <div id="mylilNav" class="verticaloverlay">

    <a href="javascript:void(0)" class="closebtn" onclick="closelilNav()"></a>
    <div class="closingcross">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#143673" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="18" y1="6" x2="6" y2="18"/>
        <line x1="6" y1="6" x2="18" y2="18"/>
      </svg>
    </div>
    <ul class="overlay-content">

      <div class="row bigbigspace">
        <div class="col-xs-2">
          <%= link_to user_path(current_user) do %>
          <% if current_user.facebook_picture_url.nil? %>
          <% unless current_user.profile_picture.nil?  %>
          <% if current_user.profile_picture.present? %>
          <%= cl_image_tag current_user.profile_picture, class: "avatar-nav", crop: :fill %>
          <% else %>
          <%= image_tag("default.png", class: "avatar-nav") %>
          <% end %>
          <% end %>
          <%else %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar-nav", crop: :fill %>
          <% end %>
          <% end %>
        </div>
        <div class="col-xs-10">
          <ul class="list-inline profile liltop">
            <li><%= current_user.first_name.capitalize %></li>
            <li class="profile-inline"><%= current_user.last_name.capitalize %></li>
            <li class="little-dates"><%= current_user.user_score %></li>
          </ul>
          <%= link_to destroy_user_session_path, class: "profile opacity",  method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </div>
      </div>
      <li class="little-title">MY TRIPS</li>
      <ul class="cities yes">
        <% current_user.teams.each do |t| %>
        <% if t.in_trip? %>
        <% if t.city.present? %>
        <li> <ul class="list-inline"><li><%= link_to t.city.name, team_path(t), method: :get %></li>
        <li class="little-dates"><%= t.start_date.strftime("%d")%> <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
          <%= t.end_date.strftime("%d-%m") %></li></ul>
        </li>
        <% end %>
        <% end %>
        <% end %>
      </ul>
      <li class="cities"><%= link_to "New trip", root_path %></li>
      <li><hr class="opacity" align="left" width="10%"></li>
      <%#= link_to "Edit my profile", edit_user_path(current_user)%>
      <li>About</li>
      <li>Contact us</li>
<!--           <li><ul class="list-inline">
            <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
            <li><i class="fa fa-instagram" aria-hidden="true"></i></li>
            <li><i class="fa fa-youtube" aria-hidden="true"></i></li>
            <li><i class="fa fa-twitter" aria-hidden="true"></i></li>
          </ul></li> -->
        </ul>
      </div>
    </div>

    <% else %>
    <div class="navbar-item hidden-md hidden-lg">

    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "loginpls", style: "z-index:15;" %>

<!--       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#333333
      " stroke-width="2" stroke-linecap="round" stroke-linejoin="round" onclick="openlilNav()">
      <line x1="3" y1="12" x2="21" y2="12"/>
      <line x1="3" y1="6" x2="21" y2="6"/>
      <line x1="3" y1="18" x2="21" y2="18"/>
    </svg>

    <div id="mylilNav" class="verticaloverlay">
      <a href="javascript:void(0)" class="closebtn" onclick="closelilNav()"></a>
      <div class="closingcross">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#333333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"/>
          <line x1="6" y1="6" x2="18" y2="18"/>
        </svg>
      </div>
      <ul class="overlay-content">
        <div class="row bigbigspace">
          <li></li>
          <li><hr class="opacity" align="left" width="10%"></li>
          <li>About</li>
          <li>Contact us</li>
        </div>
      </ul>
    </div> -->
  </div>
  <% end %>

  <% end %>

</div>
</div>