config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/models/city.rb
class City < ApplicationRecord


  has_many :challenges
  has_many :teams
  validates :name, presence: true

  has_attached_file :cover_pic, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :cover_pic, content_type: /\Aimage\/.*\z/

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = policy_scope(City)

  end

  def show

    @city = City.find(params[:id])
    authorize @city
  end

 def weather
  session[:return_to] ||= request.referer

    @city = City.find(params[:city_id])
    authorize @city
  end

  private
  def city_params
    params.require(:city).permit(:name, :picture, :country, :advice, :id )
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/.pour la liste des ville.html.erb
<div class="row">
  <div class="col-xs-7">
    <%@cities.each do |city| %>
    <p><%= image_tag city.picture, height: 50, width: 150, crop: :fill %> - <%= city.name %></p>
    <% end %>

  </div>
</div>

app/views/cities/index.html.erb
<h1>Where do you want to go</h1>

<div class="row">
  <div class="col-xs-7">
    <%@cities.each do |cit| %>
    <p><%= image_tag cit.picture, height: 50, width: 150, crop: :fill %> - <%=link_to city.name, city_path(cit.id) %></p>
    <% end %>

  </div>
</div>

<div id="cont_OTYzMDd8NXwxfDF8MnxGRkZGRkZ8Mnw2NjY2NjZ8Y3wx"><div id="spa_OTYzMDd8NXwxfDF8MnxGRkZGRkZ8Mnw2NjY2NjZ8Y3wx"><a id="a_OTYzMDd8NXwxfDF8MnxGRkZGRkZ8Mnw2NjY2NjZ8Y3wx" href="http://www.meteocity.com/belgique/bruxelles_v96307/" target="_blank" style="color:#333;text-decoration:none;">Météo Bruxelles</a> ©<a href="http://www.meteocity.com">meteocity.com</a></div><script type="text/javascript" src="http://widget.meteocity.com/js/OTYzMDd8NXwxfDF8MnxGRkZGRkZ8Mnw2NjY2NjZ8Y3wx"></script></div>

app/views/cities/show.html.erb
 <div class="container text-center">
<div class="row answer-title">
<%= link_to '', session[:return_to], class: "fa fa-times fa-lg cross-challenge-answer", style: "color: #blue;" %>
<br>
<h1>Advices before your tripin Brussels</h1>
<br>


<p>Brussels is a multicultural, medieval delight. While the de facto capital of the European Union plays host to 14 million business travellers each year, the unique city has plenty to offer vacationers and wonderful places to stay. Hire a bike, jump on a tram or head out on foot to explore its cobblestoned squares, evening markets and glorious Art Nouveau architecture.</p>



<h2>1. About Brussels Airport </h2>

<p>Why wait for your Belgian adventure to begin? After collecting your luggage at Brussels Airport, enjoy your first Belgian beer and waffles at Hi! Brussels in the arrivals hall.</p>

<p>The busy airport is expansive enough to need 2.5 km of moving walkways, but you can make navigation a snap by downloading the Brussels Airport mobile app. It can help you find your luggage, map out your route to the exit and find food and drink discounts. Prior to your departure from Brussels, use the app to check live security wait times, track your flight and find out about gate changes.</p>

<p>To get to the city, head downstairs to the train station; a single journey takes about 20 minutes. Taxis are available as well, but can be costly at around €45 for the trip.</p>



<h2>2. Technology Needs</h2>

<p>Belgium electricity operates on 230 volts, 50 Hz, using standard European two-pin round-prong plugs that fit into recessed wall sockets. To avoid any delay in recharging your devices, buy an adaptor before leaving for your trip so you can plug right in upon arrival.</p>

<p>Some public spaces are starting to offer free Wi-Fi, and certain cafés provide it to customers. As of now, however, it’s by no means widespread or reliable. If you value regular connectivity, look into buying a local SIM card with mobile data included.</p>



<h2>3. Getting Around Brussels</h2>

<p>Getting around Brussels is easy, with several transit options available for visitors. Avoid having to get a ticket for every trip with a twenty-four-hour travel pass (known as a Jump ticket). It costs €7.50 and gives you unlimited use of trams, buses and the metro. You can buy them from machines at most transit stops or from kiosks at the bigger interchanges. Simply swipe it on the red box every time you get on a bus or tram, or at the gates to underground stations.</p>

<p>Alternately, try Villo!, the Brussels bike sharing system, to get an up-close view of the city as you travel. Simply rent a bike from one of 180 stations, ride it to your destination and return it to a nearby station.</p>




<h2>4. Brussels Weather and What To Pack</h2>

<p>In Brussels, you’ll never regret stashing an umbrella in your bag before you go out. The weather, while never extreme, is changeable, and you can expect rain showers all year round. (Though of course, a downpour is the perfect excuse to seek shelter in a cosy bar or café.) And while the city’s cobblestoned streets might be picturesque, they’re tricky to navigate in anything higher than the lowest heels, so be sure to pack sensible shoes for a day’s exploring.</p>



<h2>5. Learning the Languages</h2>

<p>Belgium is multilingual—but that doesn’t mean you have to be. In the north of Belgium, they speak Dutch; in the south, it’s French. There’s even a pocket where the official language is German. And in Brussels, they speak a bit of everything.</p>

<p>Though the city is predominantly French-speaking, you’ll get by just fine in English. A French phrasebook is handy, but the city’s international flavour means you won’t struggle to find someone who speaks your language at hotels, tourist offices, bigger restaurants and stations.</p>


<h2>6. Discount Attractions</h2>

<p>To get the most out of your Brussels experience without breaking your travel budget, consider investing in a Brussels Card, which can be valid for twenty-four, forty-eight or seventy-two hours. Armed with this, you’ll get free entry to attractions, including the underground Coudenberg palace, the Musical Instruments Museum (head to the rooftop terrace for a drink with a view) and the Magritte Museum. The Brussels Card even entitles you to discounts at selected shops, restaurants and bars.</p>

<p>It’s also easy to manage: Buy it online before travelling, and store it on your phone. It doesn’t kick in until the first time you use it.</p>



<h2>7. Puckering Up</h2>

<p>Visitors are sometimes startled to see the amount of kissing going on in Brussels cafés, bars and streets. The Belgians greet each other with cheek kisses that vary according to the occasion. A simple “hello” is worth one; a birthday or other celebration merits three. You’ll see everyone from surly teenage boys to elderly ladies doing it. As a visitor, there’s no pressure on you to pucker up, but there’s also no need to stare. It’s all a part of the local culture.</p>



<h2>8. Souvenir Secrets</h2>

<p>Leave some room in your suitcase for the souvenirs you’re going to end up taking back home. Sure, beer and chocolate are the obvious Belgium choices, but don’t stop there. Try dropping into one of the ubiquitous pharmacies—look out for the green cross signs—for some interesting souvenir options. These seemingly ordinary shops are a treasure trove of top European skincare and cosmetics brands that make perfect take-home gifts.</p>




<h2>9. Proper Tipping</h2>

<p>Tipping isn’t expected in bars, cafés or taxis in Brussels. In restaurants, you might round up the bill by a couple of euros to be polite, but service charges are already included.</p>

<p>However, in the bathrooms of a bar, fast-food joint or concert hall, you might find yourself facing the formidable Madame Pipi. You’ll need to hand over fifty cents before you can use her facilities. And in a few old-school cinemas, ushers also expect a tip. Be sure to carry change for these occasions.</p>



<h2>10. Timing Excursions</h2>

<p>When planning your trip and itinerary, keep an eye on the calendar. With a few exceptions, museums are closed on Mondays, as are many restaurants. On the other hand, most shops, other than souvenir outlets and mini-markets, close on Sundays. Expect widespread closures on public holidays as well—you can find a list of public holidays here—when public transport also runs on a reduced schedule, even at the height of tourist season. </p>

</div>
</div>

app/views/cities/weather.html.erb
 <div class="container text-center">
  <div class="row answer-title">
    <h1> Week's Weather</h1>
    <%= link_to '', session[:return_to], class: "fa fa-times fa-lg cross-challenge-answer", style: "color: #blue;" %>

    <div class= "text-center-weather">
    <% if @city.name == "Brussels" %>
      <p><%= @city.name %></p>
     <div id="cont_OTYzMDd8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><div id="spa_OTYzMDd8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><a id="a_OTYzMDd8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx" href="http://www.meteocity.com/belgique/bruxelles_v96307/" target="_blank" style="color:#333;text-decoration:none;">Météo Bruxelles</a> ©<a href="http://www.meteocity.com">meteocity.com</a></div><script type="text/javascript" src="http://widget.meteocity.com/js/OTYzMDd8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"></script></div>

    <%elsif @city.name == "Paris" %>
      <p><%= @city.name %></p>
      <div id="cont_NzUwNTZ8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><div id="spa_NzUwNTZ8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><a id="a_NzUwNTZ8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx" href="http://www.meteocity.com/france/paris_v75056/" target="_blank" style="color:#333;text-decoration:none;">Météo Paris</a> ©<a href="http://www.meteocity.com">meteocity.com</a></div><script type="text/javascript" src="http://widget.meteocity.com/js/NzUwNTZ8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"></script></div>

    <%elsif @city.name == "Amsterdam" %>
      <p><%= @city.name %></p>
      <div id="cont_OTY1OTR8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><div id="spa_OTY1OTR8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><a id="a_OTY1OTR8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx" href="http://www.meteocity.com/pays-bas/amsterdam_v96594/" target="_blank" style="color:#333;text-decoration:none;">Météo Amsterdam</a> ©<a href="http://www.meteocity.com">meteocity.com</a></div><script type="text/javascript" src="http://widget.meteocity.com/js/OTY1OTR8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"></script></div>

    <%else @city.name == "London" %>
      <p><%= @city.name %></p>
      <div id="cont_OTY4MzV8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><div id="spa_OTY4MzV8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"><a id="a_OTY4MzV8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx" href="http://www.meteocity.com/royaume-uni/londres_v96835/" target="_blank" style="color:#333;text-decoration:none;">Météo Londres</a> ©<a href="http://www.meteocity.com">meteocity.com</a></div><script type="text/javascript" src="http://widget.meteocity.com/js/OTY4MzV8NXwxfDF8MXxGRkZGRkZ8M3xGRkZGRkZ8Y3wx"></script></div>
    <%end%>
    </div>
  </div>
</div>