config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :team
  attr_accessor :email

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @team = Team.find(params[:team_id])
    @member = Member.new
    authorize @team
  end

  def create
    @team = Team.find(params[:team_id])
    @user = User.find_by_email(params[:member][:email])
    if @user
      Member.create(user: @user, team: @team)
      flash[:success] = "Member added"
    else
      @email = params[:member][:email]
    end
    authorize @team
    respond_to do |format|
      format.js
      format.html {redirect_to team_path(@team)}
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @team = @member.team
    authorize @team
    @member.destroy
    redirect_to team_path(@team)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<% if user %>

<ul class="list-inline">
 <li><% if user.facebook_picture_url.nil? %>
  <% if user.profile_picture.present?  %>
  <%= image_tag user.profile_picture, class: "avatar", crop: :fill %>
  <% else %>
  <%= image_tag("default.png", class: "avatar") %>
  <% end %>
  <% else %>
  <%= image_tag user.facebook_picture_url, class: "avatar", crop: :fill %>
  <% end %></li>
  <li> <p> <%= user.first_name.capitalize %> <%= user.last_name.capitalize %>, <%= user.email %> </p></li>
</ul>
<% elsif email %>
<ul class="list-inline">
  <li><%= image_tag("default.png", class: "avatar") %></li>
  <li><p><%= email %>, <i class="fa fa-envelope-o"></i></p></li>
</ul>
<% end %>

app/views/members/create.js.erb
member = $('<%= j render("members/member", user: @user, email: @email) %>').hide();
member.appendTo($('.members-list'));
$('#member_email').val('');
member.fadeIn();

app/views/members/new.html.erb
<%= link_to team_path(@team), class: "upthere" do %>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <polyline points="15 18 9 12 15 6"/>
</svg>
<% end %>
<div class="col-xs-12 blue-bg centering">
 <h1 class="title  abitpads">Add travel buddies</h1>
</div>

<div class="content">
  <%= simple_form_for @member , url: team_members_path(@team), method: :post, remote: true, defaults: { input_html: { class: 'input-container animation-collor' } } do |f| %>
  <%= f.input :email, placeholder: "Enter the email of your travel buddy", label: 'Email of your travel buddy', wrapper: :p_wrapper %>
  <div class="topspace">
    <%= f.button :submit, 'ADD', class: "btn-circled" %>
    <% end %>
  </div>

  <div class="links">
    <div class="liltopspace">
      <ul class="members-list list-unstyled" >
        <li>
          <%#= link_to "", team_member_path(@team, @member), method: :delete, class: "fa fa-trash" %></li>
        </ul>
      </div>
    </div>
    <div class="right">
    <%= link_to 'DONE', team_path(@team), class: "btn-main"  %></div>
  </div>